# Uncomment the next line to define a global platform for your project
platform :ios, '13.2'

target 'Faces' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Faces
  pod 'SnapKit', '~> 5.0.1'

end
