# Uncomment the next line to define a global platform for your project
platform :ios, '13.2'

target 'Faces' do
  use_modular_headers!

  # Pods for Faces
  pod 'SnapKit', '~> 5.0.1'               # Auto Layout DSL
  pod 'SwiftLint', '~> 0.38.0'            # Enforce Swift style and conventions

end
